# Site
title:              Kenneth (Kenny) Mui
bio:                CS Sophomore at UW-Madison | Incoming Web Dev Intern @ FHG | Leader
description:        Hi there! Feel free to email me if you want to talk. I will try to respond within 24 hours :)
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.jpg'
navlogo:            'assets/img/Kenny.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://klmui.com/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   klmui-blog

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-150990533-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              klmui@wisc.edu
# twitter:            username
# facebook:           username
github-url:         klmui
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           kenneth-mui
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
devpost:            klmui
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
